### ISSUE TITLE
Control Panel not available in latest Build

### ISSUE THREAD

**Issue by NiccoJS** [GitHub-TC/EmpyrionWebAccess#1]
Greetings.
I reinstalled my Empyrion Server and was adding the Mod but after Following the Tutorial the webpanel isnt available anymore.

any solutions for me?

**Comment by GitHub-TC** [comment]
have you copy you savegame with the mod settings?

**Comment by NiccoJS** [comment]
Server is fresh installed and mods are installed via Tutorial.
It worked on exp10.0.4 but now the control panel wont show up.
maybe i did something wrong

**Comment by GitHub-TC** [comment]
Are out reinstall the whole server or just the EGS?
What stands in the logs Dedicated and EWA ?
Works it in the stable? Maybe they have updated the Mif.dll and the EWA needs a recomlie for the 10.0.4.

**Comment by NiccoJS** [comment]
i finaly fixed the issue.
i use an custom Solarsystem. I just need to put everything into the Scenario XXXX Folder than start EGS
Panel is now working like it should

thanks 

#closerequest
