### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by dady172172** [GitHub-TC/EmpyrionWebAccess#11]
Is there a way to reset or change the password with out reinstalling and, or a way to add users and passwords?

**Comment by GitHub-TC** [comment]
In the Users window you can  change or delete and create users with new passwords
![image](https://user-images.githubusercontent.com/18748431/94371505-52bd6c80-00f7-11eb-92db-d3d86a7d00a8.png)

**Comment by dady172172** [comment]
Oh thank you. I thought user in the list there was the main page. I feel stupid now. Thank you.
