### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH on 6.1.0.

### ISSUE THREAD

**Issue by KingPin** [GitHub-TC/EmpyrionWebAccess#13]
hi I am using EWALoader.6.1.0 from releases with empyrion 1.7.8 3720 and when I try to load the webpage on the ssl port i get the following error : 

```
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

if I goto the non-ssl port it 307 redirects me to the ssl where it errors out.

is there a way to allow using it over non-ssl? I have it accessible to lan only and see no use for an ssl cert (self signed or LE)

any help is appreciated.

**Comment by GitHub-TC** [comment]
In the appsettings.json
`"AppSettings": {
...
"UseHttpsRedirection" : false;
...
}`

and the call the configured HTTP address

**Comment by KingPin** [comment]
thank you testing this out now.

**Comment by KingPin** [comment]
it gives the following error on ssl & non ssl port now : 

`ERR_CONNECTION_REFUSED`

server log keeps pasting:

`{:EWAExtenderCommunication} ServerPipe: EWAToEmpyrionPipe47e414d089fa4cf98668c20e7eae0cf8 connected 10485760`

will test further tomorrow.

**Comment by GitHub-TC** [comment]
But there is nothing against using the default configuration which works with the self-signed certificate on HTTPS.
Then you can easily reach it via the IP address and port in the local network. Here is for example my configuration:
`
"Endpoints": {
  "Http": {
    "Url": "http://192.168.1.49:5010"
  },
  "HttpsDefaultCert": {
    "Url": "https://192.168.1.49:5011"
  }
}
`
