### ISSUE TITLE
Item ID zwischen Spiel/scenario und Webinterface stimmen nicht

### ISSUE THREAD

**Issue by dtmaster79** [GitHub-TC/EmpyrionWebAccess#18]
Hi,

wie der Titel schon sagt stimmen die Item ID's zwischen dem Webinterface und dem Game/Scenario nicht überein. Kann man das selbst Fixen oder ist das so gewollt?

Ich kann im Prinzip dadurch keine Items übers Webinterface ins Inventory der Spieler packen.

**Comment by GitHub-TC** [comment]
Du muss die Verbindung zu einer JSON Datei welche die Namen mit der Id verbindet in der EGS\Saves\Games\Savegamename\Mods\EWA\appsettings.json eintragen.
`  },
  "NameIdMappingFile": "C:\\steamcmd\\empyrion.server\\Saves\\Games\\Reforged Eden\\Mods\\EmpyrionScripting\\NameIdMapping.json",
  "Kestrel": {
`
z.B. die NameIdMapping Datei vom EmpyrionScripting
<img width="612" alt="image" src="https://github.com/GitHub-TC/EmpyrionWebAccess/assets/18748431/ddda2391-c42f-469d-bfa9-6ade76921e68">

**Comment by dtmaster79** [comment]
Also benötige ich noch den Scripting mod von dir? Muss ich diese Liste dann selbst erstellen? Das wäre mir dann zu viel Arbeit.. Grad bei Reforged Eden.

Leider hatte ich immer wieder Probleme mit dem Scripting Mod in der vergangenheit.. weswegen ich den schon länger nicht mehr benutze..
