### ISSUE TITLE
support automatic import of scenario-specific items

### ISSUE THREAD

**Issue by Vollinger0** [GitHub-TC/EmpyrionWebAccess#19]
Hi,

love this tool -and would love if we could improve it a bit. 

Currently, there is no proper way to sync the items and icons shown in EWA with the items that are configured in the currently used scenario, especially RE.
Since all the info is already on the same file system, it would be nice if there was either an import function or EWA imports that automatically.

The names of the items when you add something to an existing backpack does also not match the selected scenario at all :(

Alternatively, instead of using a mapping and then looking for the item ids, just use the names (as the game does), so we can just copy over the scenarios item icons as-is.

**Comment by GitHub-TC** [comment]
Determining the icons for the item is unfortunately quite time-consuming - I don't know when I'll have time for it. But in any case it is a worthwhile extension.

**Comment by Vollinger0** [comment]
You could even save ~4k files and the disk space if you just use them directly via a symlink. That will also help to avoid breaking out of the path served by the web server.

**Comment by GitHub-TC** [comment]
Except for a few scenario icons (even with RE there are "only" about 600) they are all available in Unity Manifest files in the bundle.
Unfortunately I don't have the time to program access to them at the moment.

Furthermore, the icon names only become apparent after processing the ECF files - a feature that was only programmed by me LONG after accessing the direct icons.

Again, the lack of time is the reason why the few icons of the scenario are not used
