### ISSUE TITLE
EWA 4.5.7.0 system information glitch

### ISSUE THREAD

**Issue by jpa77** [GitHub-TC/EmpyrionWebAccess#2]
Hi,

noticed this after installing Ryzen 7 3700X, not sure if it existed before, available ram shows as "negative value/0"
![image](https://user-images.githubusercontent.com/44015685/61689506-ff4fd180-ad2f-11e9-9e45-d116639527f9.png)

**Comment by GitHub-TC** [comment]
How many ram do you have installed and have the windows user the permission to see that (maybe disable the UAC)

**Comment by jpa77** [comment]
> 
> 
> How many ram do you have installed and have the windows user the permission to see that (maybe disable the UAC)

32GB (4x8), tested get-ciminstance non-elevated, no problem getting memory info

**Comment by GitHub-TC** [comment]
fixed
