### ISSUE TITLE
opening backpack context menu doesn't work when selected player is offline

### ISSUE THREAD

**Issue by Vollinger0** [GitHub-TC/EmpyrionWebAccess#20]
In the main window, the sandwich-menu (3-dots) next to a backpack does not work unless there is an online player selected.

If manipulating backpacks for offline players is not a feature, i think it would help usability if there was a tool tip or a hint.

The error shown is:
```main-es2015.14ea8c120486025b2a94.js:1 ERROR Error: matMenuTriggerFor: must pass in an mat-menu instance.

    Example:
      <mat-menu #menu="matMenu"></mat-menu>
      <button [matMenuTriggerFor]="menu"></button>
    at main-es2015.14ea8c120486025b2a94.js:1:2574850
    at t._checkMenu (main-es2015.14ea8c120486025b2a94.js:1:2575026)
    ...
```

**Comment by GitHub-TC** [comment]
I can only deactivate the menu items here because the central three items stand for all submenus of the tab and some functions can also be selected in offline mode.
