### ISSUE TITLE
link to playfield structure list does not work as expected

### ISSUE THREAD

**Issue by Vollinger0** [GitHub-TC/EmpyrionWebAccess#21]
In the main window, the column "Playfield":
![image](https://github.com/GitHub-TC/EmpyrionWebAccess/assets/148711063/4d1219a2-4764-4b11-b743-b71536bab67a)
... of the current player shows the tooltip "Structures of $playername" which then links to the structure overview, with the filter being pre-set to $playername. That structure filter though, does not work for the players name.

Options: I'd suggest to either change the link, so that it shows the structures of that playfield instead (and change tooltip accordingly). Or make the filter work for the structure list for player names too :)

**Comment by GitHub-TC** [comment]
Right I will add another one at the faction which then presets the faction and correct this one

**Comment by GitHub-TC** [comment]
EWA 7.0.3
And the filter combine this
<img width="983" alt="image" src="https://github.com/GitHub-TC/EmpyrionWebAccess/assets/18748431/0c52df95-a0fe-4d6d-bc6f-e9fabfa7e01d">

**Comment by GitHub-TC** [comment]
https://github.com/GitHub-TC/EmpyrionWebAccess/releases/tag/7.0.3
