### ISSUE TITLE
Fehler nach Spielupdate

### ISSUE THREAD

**Issue by kuliban** [GitHub-TC/EmpyrionWebAccess#23]
Es können keine ersten Dateien für die neue Version des Spiels erstellt werden

**Comment by GitHub-TC** [comment]
Was meinst du mit "erste" Dateien? Die Spielinitialisierung wird von Empyrion selber durchgeführt da hat der EWA nichts mit zu tun - ggf. muss man bei einer komplett frischen Installation EWA und Spiel herunterfahren und neu starten.

**Comment by kuliban** [comment]
die Datei „start.txt“ fehlt einfach
