### ISSUE TITLE
Problem with Timetable and Backups

### ISSUE THREAD

**Issue by gkleinfe** [GitHub-TC/EmpyrionWebAccess#3]
I have the server running with the EWA.  I can restart the server in the web app.  I'm trying to schedule server restarts that include backing up the game and resetting deposits in my playfields.  It does not seem to be backing anything up and deposits are defintely not getting reset.  I've include a couple of screenshots to show what I'm trying to do.

![TimeTable](https://user-images.githubusercontent.com/3876224/63312923-e572c180-c2d0-11e9-8dca-0f2cc57d1122.png)

![Restore](https://user-images.githubusercontent.com/3876224/63313021-194de700-c2d1-11e9-9049-50f97003c67a.png)

**Comment by GitHub-TC** [comment]
For the restart capabilities you have to configure the startcommand too.
![image](https://user-images.githubusercontent.com/18748431/63320253-740d3000-c31d-11e9-85d7-5b42e28dddfb.png)

**Comment by gkleinfe** [comment]
I'm not having a problem at all with manual restart capabilities.

I'm not able to backup or reset deposits during the automatic restart as described in my timetable image.  I am seeing nothing in my restore section afterwards.

**Comment by gkleinfe** [comment]
I figured out what was wrong.  All on my part.  

On the restore page, I couldn't see and backpacks or factory items to restore because no on was logged in.  Users must be logged in to see and act upon these items.

I also couldn't see any items on the other tabs of the restore page because I didn't select a back from which to see the items in the drop down.  It just wasn't obvious at first.

On the timetable page, it would be nice to have more granular reset options.  A few that I can think of are reset deposits, reset asteroids, reset POI.  Currently, we have to reset the entire playfield.  On a small server like mine, I don't mind if people tunnel their bases into the ground.  This would allow that without having to dig themselves out at every reset.

**Comment by GitHub-TC** [comment]
The function you search is "Wipe playfields" - these use the "wipe" command with can be configurated to poi, deposit, terrain, and/or player
